# Generated by Django 3.1.2 on 2020-10-30 21:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20201021_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
